BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE XUSER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/



CREATE TABLE XUSER (
	EMAIL VARCHAR2(100) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR2(100) DEFAULT '1234'
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE XBOARD';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/



CREATE TABLE XBOARD (
	ID NUMBER(10,0) NOT NULL PRIMARY KEY,
	WRITER VARCHAR2(100) DEFAULT NULL,
	TITLE VARCHAR2(255) DEFAULT NULL,
	CONTENT VARCHAR2(4000) DEFAULT NULL,
	REG_DATE DATE DEFAULT NULL,
	HIT_COUNT NUMBER(10,0) DEFAULT 0
);



BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE XBOARD_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/



CREATE SEQUENCE XBOARD_SEQ
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	NOCACHE;





